#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" << EOF
CREATE USER ${PROJECT_DB_USER} WITH ENCRYPTED PASSWORD '${PROJECT_DB_USER_PASS}';
CREATE DATABASE ${PROJECT_DB};
GRANT ALL PRIVILEGES ON DATABASE ${PROJECT_DB} TO ${PROJECT_DB_USER};
\c ${PROJECT_DB} ${POSTGRES_USER}
GRANT ALL ON SCHEMA public TO ${PROJECT_DB_USER};
EOF
# line "<< \c ${PROJECT_DB} ${POSTGRES_USER}" == "You are now connected to database "${PROJECT_DB}" as user "${POSTGRES_USER}"."
